levelMap = [
[
"                                                                                                                                                                                                                                   ",
"                                                                                                                                                                                                                                   ",
"                                                                                                                                                                                                                                   ",
"                                                                                                                                                                                                                                   ",
"                                                                                                                                                                                                                                   ",
"                                                                                                                                                                                                                                   ",
"                                                                                                                                                                                                                                   ",
"                                                                                                                                                                                                                                   ",
"                                                                                                               N                                                                                                                   ",
"         C C                 Q            C                                                                   NN                                                                                                                   ",
"         MMMQ                            MMM     MQQM          C               C                             NNN                                                                                                                   ",
"                                                                                            C               NNNN                                                                                                                   ",
"            C      C                  C           C           N  N          NN  N           MMQM           NNNNN         F                                                                                                         ",
"            M      MM     Q  Q  Q     M           MM         NN  NN        NNN  NN      C            C    NNNNNN                                                                                                                   ",
"                                                            NNN  NNN      NNNN  NNN    34           34   NNNNNNN                                                                                                                   ",
"  P    C    C  C                            C      C       NNNN  NNNN C  NNNNN  NNNN   12  C  C     12  NNNNNNNN         N                                                                                                         ",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"],
[
"                                                               NNNNNNNNNNNN                                                                                                                                                                                                              ",
"                                                               NNNNNNNNNNNN                                                                                                                                                                                                              ",
"                                                               NNNNNNNNNNNN                                                                                                                                                                                                              ",
"                                                               NNNNNN                                           CCC                                                                                                                                                                      ",
"                          CCCC                                 NNN                                            MMMMM                                                                                                                                                                      ",
"                          MMQM                                 N                                        CC                                                                                                                                                                               ",
"                                                               N        CC      C                       34                                                                                                                                                                               ",
"                             C                                 N      NNNN C                      CC    12                                                                                                       MM                                                                      ",
"                          MMMM      CC                         NC    NNNNNNN                      34    12                                                 CC                                           CCC                                                                              ",
"                    CC             MMM    C                    NNN   NNNNNNN                 CC   12    12           C      C                                                                           MMMM M                                                                           ",
"                   MMM                   MMM     MQQM          NN    NNNNNNN                 34   12    12           MMMQQQMM                                                               C                                               N                                            ",
"            CC                                                 N    NNNNNNNN           CC    12   12    12                                            NNNN    NNNN                        MMM    C         CC                              NN                                            ",
"           MMM                        C           C                NNNNNNNNN           34    12   12    12                         CC                NNNNN    NNNNN               CCC            N     MMMMMM                             NNN       F                                    ",
"       C                              M           MM    CC        NNNNNNNNNN        C  12    12   12    12                      MMMMMMM             NNNNNN    NNNNNN            MMMMQ           NNN                                      NNNN                                            ",
"      34                                                34      NNNNNNNNNNNN        M  12    12   12    12                                   34    NNNNNNN    NNNNNNN                          NNNNN                               34   NNNNN                                            ",
"  P   12                                    C      C    12     NNNNNNNNNNNNN   MM      12    12   12    12                      CCCCCCCCCCCCC12   NNNNNNNN    NNNNNNNN  CCCC                  NNNNNNN                              12  NNNNNN       N                                    ",
"XXXXXXXXXXXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXX    XX   XX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       XXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXX                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXXX    XX   XX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       XXXXX    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]]

tileSize = 32
surfaceWidth = 750
surfaceHeight = len(levelMap[0]) * tileSize